name: C/C++ CI

on: push

jobs:
  build:
    container: henriquegemignani/docker-devkitpro-nintendont
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
