name: C/C++ CI

on: push

jobs:
  build:
    container: ghcr.io/randovania/docker-devkitpro-nintendont:main
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
