name: C/C++ CI

on: 
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    

jobs:
  build:
    container: ghcr.io/randovania/docker-devkitpro-nintendont:main
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: make
      run: make

    - name: Upload the dol
      uses: actions/upload-artifact@v4
      with:
        path: loader/loader.dol

  test:
    container: ghcr.io/randovania/docker-devkitpro-nintendont:main
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: recursive

    - name: Set compiler env vars
      run: |
        echo "CC=$DEVKITPPC/bin/powerpc-eabi-gcc" >> $GITHUB_ENV
        echo "CXX=$DEVKITPPC/bin/powerpc-eabi-g++" >> $GITHUB_ENV

    - name: Compile tests
      run: |
        cmake -S ./test -B ./test/build
        make -C test/build
    
    - name: Run tests
      run: ./test/build/test_exec
