name: C/C++ Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    container: henriquegemignani/docker-devkitpro-nintendont
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: loader/loader.dol
        asset_name: boot.dol
        tag: ${{ github.ref }}
        overwrite: true
        body: "Relase executable"